language: node_js
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"
node_js:
  - "10"
script:
  - yarn test
  - yarn deploy
  - ls -l build/* build.zip
  - sha256sum build.zip | tee SHA256SUMS.txt
  - find build -type f -exec ls {} \; | sort -f | xargs sha256sum | tee -a SHA256SUMS.txt
  - find build -type f -exec ls {} \; | sort -f | xargs cat | sha256sum | tee -a SHA256SUMS.txt
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - build.zip
    - SHA256SUMS.txt
  skip_cleanup: true
  on:
    tags: true
