version: 2
references:
  yarn_key: &yarn_key
    v1-dependencies-{{ checksum "yarn.lock" }}

  save_yarn_cache: &save_yarn_cache
    save_cache:
      key: *yarn_key
      paths:
        - node_modules

  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      key: *yarn_key

jobs:
  build-test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore_yarn_cache
      - run: yarn --ignore-engines
      - *save_yarn_cache
      - run: yarn lint:ts
      - run: yarn test
      - run: yarn deploy
      - run: ls -l build/* build.zip
      - run: sha256sum build.zip | tee SHA256SUMS.txt
      - run: find build -type f -exec ls {} \; | sort -f | xargs sha256sum | tee -a SHA256SUMS.txt
      - run: find build -type f -exec ls {} \; | sort -f | xargs cat | sha256sum | tee -a SHA256SUMS.txt
      - run: mkdir dist && mv build.zip SHA256SUMS.txt dist
      - store_artifacts:
          path: dist
          destination: dist

  publish:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore_yarn_cache
      - run: yarn install
      - *save_yarn_cache
      - run: yarn deploy
      - run: yarn upload:chrome
      - run: yarn publish-extension

workflows:
  version: 2
  build:
    jobs:
      - build-test:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
